fix

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -33,13 +33,13 @@ jobs:
           redocly bundle api-specs/api-v1.yaml --output docs/bundled-api-v1.yaml || exit 1
           redocly build-docs docs/bundled-api-v1.yaml --output docs/index.html || exit 1
 
-      # # Verify Docs Output
-      # - name: Verify Docs Output
-      #   run: |
-      #     if [ ! -s docs/index.html ]; then
-      #       echo "Error: Documentation build failed or output is empty."
-      #       exit 1
-      #     fi
+      # Verify Docs Output
+      - name: Verify Docs Output
+        run: |
+          if [ ! -s docs/index.html ]; then
+            echo "Error: Documentation build failed or output is empty."
+            exit 1
+          fi
 
       # # Deploy to GitHub Pages
       # - name: Deploy to GitHub Pages
